name: QuickCamp
version: '1.9b'
main: com.northvik.quickCamp.QuickCamp
api-version: '1.20'
authors: [ Viktor ]
description: Quick Camp plugin.
depend:
  - WorldEdit
  - WorldGuard
softdepend:
  - Towny
  - GriefPrevention

commands:
  camp:
    description: Main command for managing camps
    permission: quickcamp.camp
    permission-message: You do not have permission to use this command!

permissions:
  quickcamp.camp:
    description: Grants access to the base /camp command
    default: true
  quickcamp.camp.gui:
    description: Grants access to /camp gui
    default: op
  quickcamp.camp.place:
    description: Grants access to /camp place
    default: op
  quickcamp.camp.help:
    description: Grants access to /camp help
    default: op
  quickcamp.camp.give:
    description: Grants access to /camp give
    default: op

